#!/usr/bin/env bash
mpv \
--idle \
--geometry=50%x44%+100%+0% \
--keep-open=always \
--script=$MBROWSER_HOME/mpv/scripts/init.lua \
--input-conf=$MBROWSER_HOME/mpv/input.conf \
--input-ipc-server=$MBROWSER_SOCKET \
